### ISSUE TITLE
Home Assistant - Energy Values from SA are incorrect

### ISSUE THREAD

**Issue by Roving-Ronin** [PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring#11]
Hi Peter,

Just noticed that there's a bunch of errors in my HA logs (supervised v2023.1.4) in regards your integration:

Error Log____________________________________________________________________________

Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:385
Integration: Sensor (documentation, issues)
First occurred: 1:25:10 am (4 occurrences)
Last logged: 2:25:10 am

Entity sensor.sa_todays_energy_generated_total from integration template has state class total_increasing, but its state is negative. Triggered by state -13 with last_updated set to 2023-01-14T14:19:59.999999+00:00. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22

Entity sensor.sa_todays_energy_generated_total_kwh from integration template has state class total_increasing, but its state is negative. Triggered by state -0.016 with last_updated set to 2023-01-14T14:28:13.216322+00:00. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22

Entity sensor.sa_todays_energy_generated_expected_total from integration template has state class total_increasing, but its state is negative. Triggered by state -19 with last_updated set to 2023-01-14T15:23:13.298357+00:00. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22

Entity sensor.sa_todays_energy_generated_expected_total_kwh from integration template has state class total_increasing, but its state is negative. Triggered by state -0.019 with last_updated set to 2023-01-14T15:23:13.299490+00:00. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22

End Log____________________________________________________________________________

Just looking through the existing issues opened for other integrations and there's a few like this, such as https://github.com/home-assistant/core/issues/56188 This one has also spawned a feature request to allow negative energy values (but it seems to be going nowhere), see: https://community.home-assistant.io/t/allow-negative-power-energy-in-energy-dashboard/327724 but does have some work arounds (new sensors converting negative to positive values), 

This all aligns with HA Energy Dashboard supposed to be getting postive values from solar production and export, that it then recognises each as being import vs export etc (even if all showing a positive number), see: 
https://www.home-assistant.io/images/blog/2021-08-energy/sidebar-widgets.png
https://www.home-assistant.io/images/blog/2021-08-energy/energy-usage.png
https://demo.home-assistant.io/#/energy

Looking through the sa_live_site_data, though it appears the data from SA is all showing as positive numbers:
i.e.
                    - consumed: 9124.63
                                        count: 6
                       generated: 8296.21
t_stamp: '2023-01-15T05:21:55Z'_

and the same for sa_data_by_5min
i.e.
   - energy_consumed: 116.7194
         energy_generated: -0.9231
 t_stamp: '2023-01-15 00:00:00'

Looking through you yaml file, I can't see anywhere that you have told it to negate the value, turning a + into a - number either, or did I miss something?

==================================================

Also reviewing the HA documentation and it appears that the data we are supposed to be using for the Energy Dashboard inputs is the accumulating energy feeds, and not the daily feeds. This is in line with all the individual device (plugs) and gas/water meters feeding into the dashboard, that give an ever increasing reading (and aligns with the 'state_class: total_increasing' and how it is supposed to work).

Would you know if there is a accumulating energy total for import / export / production from SA, they must have the data within SA, as they use this to be able to review annual data on their dashboard? Or alternatively, are additional sensors needed to be added, that are 'total_increasing' and simply keep adding on the values from:

sensor.sa_todays_energy_generated_total
sensor.sa_todays_energy_consumed_total
sensor.sa_todays_energy_exported

to become:

sensor.sa_total_energy_generated
sensor.sa_total_energy_consumed
sensor.sa_total_energy_exported

?

**Comment by PeterH24x7** [comment]
@Roving-Ronin - plenty to catch-up on here and before. Any chance we can have an online meet-greet and discuss - e.g. Zoom. Maybe an evening later this week?

As a quick point of note your example above for sa_data_by_5min does have a negative value for energy generated (i.e. -0.9231) in the previous 5 mins.  As such the resulting sum of the 5 min generation data for the day would be net negative. Despite the negative on the generation data it does all seem to work correctly in the HA EM - and matches well with the weekly, monthly and yearly totals I get from SA itself. My $ totals based on realtime Amber rate calculations also tally quite well.

To add to the conundrum of what to do, when the inverter shuts down later in the day SA does show minor inverter energy consumption and therefore this value becomes positive (just now at 8.25pm this evening my 5-min generation is reading positive 3.2289 Wh).  
```
- energy_consumed: 42.6267
  energy_generated: 3.2289
  load_air_conditioner: 1.3019
  load_ev_charger: 0.4269
  load_hot_water: 0.1728
  load_stove: 0.1139
  t_stamp: '2023-01-15 20:25:00'
```

**Comment by Roving-Ronin** [comment]
Hi Peter,

Apologies I've been flat out. I do think your right, as my 2 inverters each pull about 10w when in standby mode. Apologies it didn't 'click' and correlate with me, I was more concentrating on how can we just it to stop throwing errors and if there was some other class state more applicable. 

On the other point, your correct the daily energy does work, just comparing to developer how to in HA and seeing they say it should be this ever accumulating sensor data that should be used, and let scratching my head ..should it be done that way / whats wrong with the daily / does it affect something else 'downstream' or long term.

Apologies.
