### ISSUE TITLE
ValueError: Sensor sensor.sa_todays_hot_water_generated

### ISSUE THREAD

**Issue by menaibluey** [PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring#18]
Hi,

I'm getting the following error. Any idea what causing this? I do have a hot water channel for solar re-direction to my HWS. Any other logs you would need?

2024-02-23 12:55:48.302 ERROR (MainThread) [homeassistant.helpers.event] Error while dispatching event for sensor.sa_data_by_5min_time_stamp to <Job track state_changed event {'sensor.sa_data_by_5min_load_hot_water_generated', 'sensor.sa_data_by_5min_energy_consumed', 'sensor.sa_data_by_5min_time_stamp', 'sensor.sa_data_by_5min_load_hot_water', 'sensor.sa_todays_hot_water_generated', 'sensor.sa_data_by_5min_load_ev_charger', 'sensor.sa_data_by_5min_energy_generated'} HassJobType.Callback <bound method TrackTemplateResultInfo._refresh of <TrackTemplateResultInfo {Template<template=({{- states.sensor.sa_data_by_5min_load_hot_water_generated.state -2024-02-23 12:55:48.302 ERROR (MainThread) [homeassistant.helpers.event] Error while dispatching event for sensor.sa_data_by_5min_time_stamp to <Job track state_changed event {'sensor.sa_data_by_5min_load_hot_water_generated', 'sensor.sa_data_by_5min_energy_consumed', 'sensor.sa_data_by_5min_time_stamp', 'sensor.sa_data_by_5min_load_hot_water', 'sensor.sa_todays_hot_water_generated', 'sensor.sa_data_by_5min_load_ev_charger', 'sensor.sa_data_by_5min_energy_generated'} HassJobType.Callback <bound method TrackTemplateResultInfo._refresh of <TrackTemplateResultInfo {Template<template=({{- states.sensor.sa_data_by_5min_load_hot_water_generated.state -}}) renders=14>: <RenderInfo Template<template=({{- states.sensor.sa_data_by_5min_load_hot_water_generated.state -}}) renders=14> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'sensor.sa_data_by_5min_load_hot_water_generated'}) rate_limit=None has_time=False exception=None is_static=False>, Template<template=(total_increasing) renders=1578>: <RenderInfo Template<template=(total_increasing) renders=1578> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset() rate_limit=None has_time=False exception=None is_static=True>, Template<template=({{- states.sensor.sa_data_by_5min_time_stamp.state -}}) renders=994>: <RenderInfo Template<template=({{- states.sensor.sa_data_by_5min_time_stamp.state -}}) renders=994> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'sensor.sa_data_by_5min_time_stamp'}) rate_limit=None has_time=False exception=None is_static=False>, Template<template=({%- if ( states.sensor.sa_data_by_5min_load_hot_water.state|is_number ) 
    and ( states.sensor.sa_data_by_5min_energy_consumed.state|is_number ) 
    and ( states.sensor.sa_data_by_5min_energy_generated.state|is_number ) 
    and ( states.sensor.sa_data_by_5min_load_ev_charger.state|is_number )
    and ( states.sensor.sa_data_by_5min_load_air_conditioner.state|is_number )
  -%}
  {%- if states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0) > 0.0 -%} 
    {%- if (states.sensor.sa_data_by_5min_energy_generated.state|float(0.0)) >= 
        ( (states.sensor.sa_data_by_5min_energy_consumed.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_ev_charger.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_air_conditioner.state|float(0.0)) ) 
      -%}
      {{- states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0) -}}
    {%- elif (states.sensor.sa_data_by_5min_energy_generated.state|float(0.0)) >
        ( (states.sensor.sa_data_by_5min_energy_consumed.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_ev_charger.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_air_conditioner.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0)) ) 
      -%}
      {{- (states.sensor.sa_data_by_5min_energy_generated.state|float(0.0))
          - ( (states.sensor.sa_data_by_5min_energy_consumed.state|float(0.0))
            - (states.sensor.sa_data_by_5min_load_ev_charger.state|float(0.0))
            - (states.sensor.sa_data_by_5min_load_air_conditioner.state|float(0.0)) 
            - (states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0)) ) 
        -}}
    {%- else -%}
      0.0
    {%- endif %}
  {%- else -%}
    0.0
  {%- endif -%}
{%- else -%}
  {{- state_attr( 'sensor.sa_todays_hot_water_generated', 'hw_energy_last5min' ) 
      if states.sensor.sa_todays_hot_water_generated.attributes.hw_energy_last5min|is_number 
      else "0.0" 
    -}}
{%- endif -%}) renders=2264>: 
    and ( states.sensor.sa_data_by_5min_energy_consumed.state|is_number ) 
    and ( states.sensor.sa_data_by_5min_energy_generated.state|is_number ) 
    and ( states.sensor.sa_data_by_5min_load_ev_charger.state|is_number )
    and ( states.sensor.sa_data_by_5min_load_air_conditioner.state|is_number )
  -%}
  {%- if states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0) > 0.0 -%} 
    {%- if (states.sensor.sa_data_by_5min_energy_generated.state|float(0.0)) >= 
        ( (states.sensor.sa_data_by_5min_energy_consumed.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_ev_charger.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_air_conditioner.state|float(0.0)) ) 
      -%}
      {{- states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0) -}}
    {%- elif (states.sensor.sa_data_by_5min_energy_generated.state|float(0.0)) >
        ( (states.sensor.sa_data_by_5min_energy_consumed.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_ev_charger.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_air_conditioner.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0)) ) 
      -%}
      {{- (states.sensor.sa_data_by_5min_energy_generated.state|float(0.0))
          - ( (states.sensor.sa_data_by_5min_energy_consumed.state|float(0.0))
            - (states.sensor.sa_data_by_5min_load_ev_charger.state|float(0.0))
            - (states.sensor.sa_data_by_5min_load_air_conditioner.state|float(0.0)) 
            - (states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0)) ) 
        -}}
    {%- else -%}
      0.0
    {%- endif %}
  {%- else -%}
    0.0
  {%- endif -%}
{%- else -%}
  {{- state_attr( 'sensor.sa_todays_hot_water_generated', 'hw_energy_last5min' ) 
      if states.sensor.sa_todays_hot_water_generated.attributes.hw_energy_last5min|is_number 
      else "0.0" 
    -}}
{%- endif -%}) renders=2264> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'sensor.sa_data_by_5min_energy_consumed', 'sensor.sa_data_by_5min_load_hot_water', 'sensor.sa_todays_hot_water_generated', 'sensor.sa_data_by_5min_load_ev_charger', 'sensor.sa_data_by_5min_energy_generated'}) rate_limit=None has_time=False exception=None is_static=False>, Template
    and ( states.sensor.sa_data_by_5min_load_hot_water_total.state|is_number ) 
  -%}
  {% if ( states.sensor.sa_data_by_5min_load_hot_water_total.state|float(0.0) > 0.0 ) -%}
    {{- (( states.sensor.sa_data_by_5min_load_hot_water_generated.state|float(0.0) ) 
        / (states.sensor.sa_data_by_5min_load_hot_water_total.state|float|default('none')) * 100.0 ) | int 
      -}}
  {%- else -%}
    none
  {%- endif -%}
{%- else -%}
  none
{%- endif -%}) renders=18>: 
    and ( states.sensor.sa_data_by_5min_load_hot_water_total.state|is_number ) 
  -%}
  {% if ( states.sensor.sa_data_by_5min_load_hot_water_total.state|float(0.0) > 0.0 ) -%}
    {{- (( states.sensor.sa_data_by_5min_load_hot_water_generated.state|float(0.0) ) 
        / (states.sensor.sa_data_by_5min_load_hot_water_total.state|float|default('none')) * 100.0 ) | int 
      -}}
  {%- else -%}
    none
  {%- endif -%}
{%- else -%}
  none
{%- endif -%}) renders=18> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'sensor.sa_data_by_5min_load_hot_water_generated'}) rate_limit=None has_time=False exception=None is_static=False>, Template:  all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset() rate_limit=None has_time=False exception=None is_static=True>}>>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 664, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'unknown'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 667, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unknown'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 296, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 700, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1215, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
  File "/usr/src/homeassistant/homeassistant/core.py", line 700, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 434, in _handle_results
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1047, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 995, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 671, in state
    raise ValueError(
ValueError: Sensor sensor.sa_todays_hot_water_generated has device class 'energy', state class 'None' unit 'Wh' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' ()}}) renders=14>: <RenderInfo Template<template=({{- states.sensor.sa_data_by_5min_load_hot_water_generated.state -}}) renders=14> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'sensor.sa_data_by_5min_load_hot_water_generated'}) rate_limit=None has_time=False exception=None is_static=False>, Template<template=(total_increasing) renders=1578>: <RenderInfo Template<template=(total_increasing) renders=1578> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset() rate_limit=None has_time=False exception=None is_static=True>, Template<template=({{- states.sensor.sa_data_by_5min_time_stamp.state -}}) renders=994>: <RenderInfo Template<template=({{- states.sensor.sa_data_by_5min_time_stamp.state -}}) renders=994> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'sensor.sa_data_by_5min_time_stamp'}) rate_limit=None has_time=False exception=None is_static=False>, Template<template=({%- if ( states.sensor.sa_data_by_5min_load_hot_water.state|is_number ) 
    and ( states.sensor.sa_data_by_5min_energy_consumed.state|is_number ) 
    and ( states.sensor.sa_data_by_5min_energy_generated.state|is_number ) 
    and ( states.sensor.sa_data_by_5min_load_ev_charger.state|is_number )
    and ( states.sensor.sa_data_by_5min_load_air_conditioner.state|is_number )
  -%}
  {%- if states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0) > 0.0 -%} 
    {%- if (states.sensor.sa_data_by_5min_energy_generated.state|float(0.0)) >= 
        ( (states.sensor.sa_data_by_5min_energy_consumed.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_ev_charger.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_air_conditioner.state|float(0.0)) ) 
      -%}
      {{- states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0) -}}
    {%- elif (states.sensor.sa_data_by_5min_energy_generated.state|float(0.0)) >
        ( (states.sensor.sa_data_by_5min_energy_consumed.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_ev_charger.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_air_conditioner.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0)) ) 
      -%}
      {{- (states.sensor.sa_data_by_5min_energy_generated.state|float(0.0))
          - ( (states.sensor.sa_data_by_5min_energy_consumed.state|float(0.0))
            - (states.sensor.sa_data_by_5min_load_ev_charger.state|float(0.0))
            - (states.sensor.sa_data_by_5min_load_air_conditioner.state|float(0.0)) 
            - (states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0)) ) 
        -}}
    {%- else -%}
      0.0
    {%- endif %}
  {%- else -%}
    0.0
  {%- endif -%}
{%- else -%}
  {{- state_attr( 'sensor.sa_todays_hot_water_generated', 'hw_energy_last5min' ) 
      if states.sensor.sa_todays_hot_water_generated.attributes.hw_energy_last5min|is_number 
      else "0.0" 
    -}}
{%- endif -%}) renders=2264>: 
    and ( states.sensor.sa_data_by_5min_energy_consumed.state|is_number ) 
    and ( states.sensor.sa_data_by_5min_energy_generated.state|is_number ) 
    and ( states.sensor.sa_data_by_5min_load_ev_charger.state|is_number )
    and ( states.sensor.sa_data_by_5min_load_air_conditioner.state|is_number )
  -%}
  {%- if states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0) > 0.0 -%} 
    {%- if (states.sensor.sa_data_by_5min_energy_generated.state|float(0.0)) >= 
        ( (states.sensor.sa_data_by_5min_energy_consumed.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_ev_charger.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_air_conditioner.state|float(0.0)) ) 
      -%}
      {{- states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0) -}}
    {%- elif (states.sensor.sa_data_by_5min_energy_generated.state|float(0.0)) >
        ( (states.sensor.sa_data_by_5min_energy_consumed.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_ev_charger.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_air_conditioner.state|float(0.0)) 
          - (states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0)) ) 
      -%}
      {{- (states.sensor.sa_data_by_5min_energy_generated.state|float(0.0))
          - ( (states.sensor.sa_data_by_5min_energy_consumed.state|float(0.0))
            - (states.sensor.sa_data_by_5min_load_ev_charger.state|float(0.0))
            - (states.sensor.sa_data_by_5min_load_air_conditioner.state|float(0.0)) 
            - (states.sensor.sa_data_by_5min_load_hot_water.state|float(0.0)) ) 
        -}}
    {%- else -%}
      0.0
    {%- endif %}
  {%- else -%}
    0.0
  {%- endif -%}
{%- else -%}
  {{- state_attr( 'sensor.sa_todays_hot_water_generated', 'hw_energy_last5min' ) 
      if states.sensor.sa_todays_hot_water_generated.attributes.hw_energy_last5min|is_number 
      else "0.0" 
    -}}
{%- endif -%}) renders=2264> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'sensor.sa_data_by_5min_energy_consumed', 'sensor.sa_data_by_5min_load_hot_water', 'sensor.sa_todays_hot_water_generated', 'sensor.sa_data_by_5min_load_ev_charger', 'sensor.sa_data_by_5min_energy_generated'}) rate_limit=None has_time=False exception=None is_static=False>, Template
    and ( states.sensor.sa_data_by_5min_load_hot_water_total.state|is_number ) 
  -%}
  {% if ( states.sensor.sa_data_by_5min_load_hot_water_total.state|float(0.0) > 0.0 ) -%}
    {{- (( states.sensor.sa_data_by_5min_load_hot_water_generated.state|float(0.0) ) 
        / (states.sensor.sa_data_by_5min_load_hot_water_total.state|float|default('none')) * 100.0 ) | int 
      -}}
  {%- else -%}
    none
  {%- endif -%}
{%- else -%}
  none
{%- endif -%}) renders=18>: 
    and ( states.sensor.sa_data_by_5min_load_hot_water_total.state|is_number ) 
  -%}
  {% if ( states.sensor.sa_data_by_5min_load_hot_water_total.state|float(0.0) > 0.0 ) -%}
    {{- (( states.sensor.sa_data_by_5min_load_hot_water_generated.state|float(0.0) ) 
        / (states.sensor.sa_data_by_5min_load_hot_water_total.state|float|default('none')) * 100.0 ) | int 
      -}}
  {%- else -%}
    none
  {%- endif -%}
{%- else -%}
  none
{%- endif -%}) renders=18> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'sensor.sa_data_by_5min_load_hot_water_generated'}) rate_limit=None has_time=False exception=None is_static=False>, Template:  all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset() rate_limit=None has_time=False exception=None is_static=True>}>>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 664, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'unknown'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 667, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unknown'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 296, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 700, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1215, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
  File "/usr/src/homeassistant/homeassistant/core.py", line 700, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 434, in _handle_results
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1047, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 995, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 671, in state
    raise ValueError(
ValueError: Sensor sensor.sa_todays_hot_water_generated has device class 'energy', state class 'None' unit 'Wh' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' ()

**Comment by PeterH24x7** [comment]
Hi @menaibluey - keen to help. Are you a new user and trying to get things going? Or are you an existing user that has been using the integration successfully and have discover a new error?
What channels do you have activated on your solar analytics device? Maybe provide me with a screenshot of what you see displayed in the Solar Analytics "My Energy Usage" page.
Rgds, Peter

**Comment by menaibluey** [comment]
Hi Peter,

 

Thanks for the quick reply. I had this going before but had to re-install my HA instance. I’m not seeing any data though in the portal even though in the State page I see the data coming through from the SA REST API.

 



 

My Energy config

 



 

States display for sensors below 

 



 



 

 

These are my channels

 



 

Let me know if you need me to run any debugs or other diagnostics. Appreciate your help. This is a tremendous piece of work. I had a go myself but gave up even though it did work somewhat. Well done!

 

Cheers

 

Markus

**Comment by menaibluey** [comment]
Thanks Peter for the offer. I’m in and out today but will upload the pictures to GitHub. Not sure what happened. If you could double check my HA Energy config to make sure I’m using the correct sensors. The ones I’m using are definitely returning data Developer Tools States it could be an issue with the Energy component as well. I’m running the latest versions. Thanks again and maybe we can catch up at a later stage. Where are you based at?CheersMarkusSent from my iPhoneOn 23 Feb 2024, at 21:09, PeterH24x7 ***@***.***> wrote:﻿
Hi Marcus - it seems there are some images missing in your reply - maybe best to edit in Github rather than reply to email?
I have time over the weekend if you wish to chat. Look me up on Facebook https://www.facebook.com/peter.hormann and send me a note on messenger to chat further.
Chrs, Peter

**Comment by menaibluey** [comment]
I'm also uploading the log as this shows more debug information.
[home-assistant.log](https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/files/14390983/home-assistant.log)

**Comment by PeterH24x7** [comment]
Hi Marcus - Seems to be something quite fundamental - poorly formatted code maybe? I would be keen for you to demo what's working/not-working. Please look me up on Facebook https://www.facebook.com/peter.hormann and send me a note on messenger to chat and share screens.

**Comment by menaibluey** [comment]
It may have something to do with my extra solar hot water channel which doesn't seem to have a sensor defined. 

The site data I'm getting back from  https://portal.solaranalytics.com.au/api/v2/site_data/xxxxx?all=true&gran=minute&trunc=false&power=false&tstart=20240224&tend=20240224 is:

       {
            "energy_generated": -1.0631,
            "energy_consumed": 23.0211,
            "t_stamp": "2024-02-24 00:00:00",
            "load_hot_water": -0.0392,
            "load_air_conditioner": 3.505,
            "**load_hot_water_solar**": 0.0503,
            "load_powerpoint": 15.7106
        },

Not sure whether this could be the issue. This channel is measuring my CatchPower sensor.

**Comment by PeterH24x7** [comment]
Hi Marcus - have you changed the code? This is the **states** display for my **sensor.sa_todays_energy_exported** and its state class is "**total_increasing**", not state class "**measurement**". Same for **sensor.sa_todays_energy_exported**.

![image](https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/91523850/8ae6c155-a082-4cdd-8466-0087bfbe6c79)

What is a **load_hot_water_solar**?

**Comment by menaibluey** [comment]
> Hi Marcus - have you changed the code? This is the **states** display for my **sensor.sa_todays_energy_exported** and its state class is "**total_increasing**", not state class "**measurement**". Same for **sensor.sa_todays_energy_exported**.
> 
> Note the units are changed to kWh via the HA lovelace config for the sensor (the base unit as per the code is nonetheless Wh).
> 
> ![image](https://private-user-images.githubusercontent.com/91523850/307501897-8ae6c155-a082-4cdd-8466-0087bfbe6c79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzA4MjYsIm5iZiI6MTcwODc3MDUyNiwicGF0aCI6Ii85MTUyMzg1MC8zMDc1MDE4OTctOGFlNmMxNTUtYTA4Mi00Y2RkLTg0NjYtMDA4N2JmYmU2Yzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDEwMjg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNzRlMGZkZWVlOWQwMmRmNjcxMjJjNTg2NjQ5MmQ1ODFjMzZhNjE0ZjE4Mjg5YzA2MTFjOGQ1YWZjNmFiM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hR295st13trGsQSwiuRYG8xHkCIhMoPL7xxkok--II0)
> 
> What is a **load_hot_water_solar**?

Nope, the code is the latest version from from GitHub file.

the load_hot_water_solar if the CatchPower channel, it's a solar diverter to the HWS. I measures the solar that's diverted to heat up the hot water.

Do you recommend to re-install the files from GitHub?

**Comment by PeterH24x7** [comment]
As in **solar_analytics.yaml**? Here's the v7 pre-release.
https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/blob/main/solar_analytics.yaml

**Comment by menaibluey** [comment]
> As in **solar_analytics.yaml**? Here's the v7 pre-release. https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/blob/main/solar_analytics.yaml

Peter, yes, I've copied solar_analystics.yaml V7 again, deleting all sensors and entities first before activating the package. Still the same issue. The sensors all have state_class: measurement, for example  

![image](https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/25679918/f757d224-e80d-4454-97f2-a35c15b6e6f4)

![image](https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/25679918/6b56de82-bda0-4d16-bf58-9717739a302a)

![image](https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/25679918/ce110404-c5fa-4f49-870a-45d03b060b63)

I haven't changed any code, that's how it's created when installed. Let me try whether Energy picks it up if I change the state_class to total_increasing.

**Comment by menaibluey** [comment]
Success! I've started a completely new HA instance and enabled your component. After a while it started to show stats and I think it's all working now. So not sure whether there's were some old entities floating around. In any case all is well now. Thanks for all your help.

![image](https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring/assets/25679918/ed62ad10-5c8a-4c03-b94f-3d35fc7103b7)

**Comment by PeterH24x7** [comment]
Hi @menaibluey - that's great news. Glad you worked it out. 

If you find my work useful/valuable, please buy me a coffee ... thank you!
[https://www.buymeacoffee.com/peter24x7](https://www.buymeacoffee.com/peter24x7)

Rgds, Peter

**Comment by PeterH24x7** [comment]
No action required.
