### ISSUE TITLE
Move SiteId to be a parameter

### ISSUE THREAD

**Issue by digitui** [PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring#2]
The site ID would be better as a parameter.
BTW: thanks for the efforts looking to contribute here

**Comment by PeterH24x7** [comment]
@digitui - thank you for your note of support and suggestion. I'm not familiar with the use of parameters in the configuration.yaml file (rather only scripts). Do you have a reference to help please?

**Comment by PeterH24x7** [comment]
Hi @digitui - I've had a go at putting the sa site id into the secrets.yaml, but then have had difficulties concatenating the site id into the resource URL field. It seems the whole URL may need to be in the secrets.yaml.  Any ideas?

**Comment by PeterH24x7** [comment]
Now fixed in release 2.
