### ISSUE TITLE
sensor.sa_todays_energy_consumed_total There is no state available for this entity. HA2022.06 

### ISSUE THREAD

**Issue by digitui** [PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring#3]
Following upgrade to HA 2022.06 

sensor.sa_todays_energy_consumed_total There is no state available for this entity.

No data is displayed in energy page

Fix issue states : 

This entity has no state at the moment, if this is an orphaned entity, you may want to remove the long term statistics of it from your database.

Do you want to permanently remove the long term statistics of sensor.sa_todays_energy_consumed_total from your database?

Investigating

**Comment by PeterH24x7** [comment]
Hi @digitui - thank you for your efforts and the advice. I've not done the upgrade as yet and will hold off making the change for the time being. Let me know if there's anything I should test in the meantime.

**Comment by digitui** [comment]
It seemed to spring into life about 8hrs after upgrading and the error went away. Presume it was something to do with the 2022.60 db upgrade.

**Comment by PeterH24x7** [comment]
@digitui - I presume this matter is now a non-issue and can be closed.
